### ISSUE TITLE
 [Android Bootcamp] Submitting week 1 assignment

### ISSUE THREAD

**Issue by nidhik** [nidhik/InstagramClone#1]
I'm submitting the week 1 assignment. /cc @codepathreview @codepath

I've listed some questions in the README, mostly related to the typical approach for displaying different types of items in one list view.

**Comment by codepathreview** [comment]
Nice job. A few notes after checking out the code:
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#progress-within-actionbar) to your app whenever a network request goes out
- Consider including a check to see if internet is available to detect any network failures. Show an approrpiate message in case of failure.
- Good to see you playing around with `RelativeLayout`. `RelativeLayout` is one of the most powerful responsive-first layout systems available across web and mobile platforms and provides better control in comparison to a linear layout.
- Consider overriding `onFailure` method in `JsonHttpResponseHandler` to handle network failures appropriately.
- Consider using the [ViewHolder pattern](http://guides.codepath.com/android/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `ListView`.
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Good to see you were able to update your image with the same proportions as on Instagram

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) which covers the most common points we see for this project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system, probably one of the most powerful responsive-first layout systems available across web and mobile platforms. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concept such as accepting user input and navigating between activities but will also reinforce important concepts such as networking, using APIs, handling remote images.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us support@codepath.com.

**P.S.** Good to see you properly added the readme with features and screenshots to your project as described in the [submitting assignments](http://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments) guide!

**Comment by nidhik** [comment]
@nesquena If you have a moment, I've listed some questions in the README, mostly related to the typical approach for displaying different types of items in one list view. 

Here are the same questions, duplicated here:

Challenges: 

I created a different layouts for list items that displayed a photo vs a video, but I wasn't happy with the way this turned out.

The ViewHolder pattern also becomes slightly less effective with this approach because you may have attached a view of the incorrect type to the recycled list item. For example, you may have to convert a recycled list item that was displaying a photo to display a video.
**What is correct approach when you want to display multiple types of views in a list?**

It also took me some time to figure out how to remove the pause/play controls of the MediaController from the video view. **Is there a better way to do this that to just set its visibility to View.GONE?**

I ended up overlaying a play button on top of the video and requiring the user to tap it to play the video. **How would you approach playing the video only when it is scrolled onto the screen and stopping it when it is scrolled off?**

**Comment by nesquena** [comment]
Hi Nidhi,

> I've listed some questions in the README, mostly related to the typical approach for displaying different types of items in one list view.

@nidhik Take a look at [this guide](http://guides.codepath.com/android/Implementing-a-Heterogenous-ListView) for the basics of how to do multiple type lists. Takes care of the recycling of views for you as well.

> It also took me some time to figure out how to remove the pause/play controls of the MediaController from the video view. Is there a better way to do this that to just set its visibility to View.GONE?

See this: http://stackoverflow.com/a/10240187/313399. You got it right more or less.

> I ended up overlaying a play button on top of the video and requiring the user to tap it to play the video. How would you approach playing the video only when it is scrolled onto the screen and stopping it when it is scrolled off?

VideoView is kind of weak actually and [doesn't take scrolling well](https://code.google.com/p/android/issues/detail?id=37229). Check out [this library](https://github.com/danylovolokh/VideoPlayerManager) for one better alternative or for manual approach, use [TextureView](https://github.com/dmytrodanylyk/dmytrodanylyk/blob/gh-pages/articles/surface-view-play-video.md).

**Comment by nidhik** [comment]
thank you Nathan!

**Comment by nesquena** [comment]
Sure of course. Good questions, I added a bit to a few of our guides and hints to make the answers more readily available in the future.
